import './js/loader.js';
import './js/form.js';
import './js/modal-registration.js';
import './js/apiServiсe.js';
// import './js/scroll.js';
import './js/modal-footer.js';
import './js/popup-modal-lib';
import './js/watched-btn.js';
import './js/queue-btn.js';
import './js/auth.js';
